# vim: set ft=yaml.ansible:
---

- name: "Set /etc/machine-id"
  become: true
  ansible.builtin.copy:
    dest: /etc/machine-id
    content: "{{ machine_id }}"
    mode: 0o444

- name: "See if /var/lib/dbus exists"
  ansible.builtin.stat:
    path: "/var/lib/dbus"
  register: dbus

# Some distributions use var/lib/dbus,
# but the directory doesn't exists on fedora
# We only need to set this file if it's not a link to /etc/machine-id
- name: "Set /var/lib/dbus/machine-id"
  become: true
  ansible.builtin.copy:
    dest: /var/lib/dbus/machine-id
    content: "{{ machine_id }}"
    mode: 0o444
  when:
    - dbus.stat.exists
    - not dbus.stat.islnk
