# vim: set ft=yaml.ansible:
---

- name: "Install make (Linux)"
  become: true
  ansible.builtin.package:
    name:
      - make
  when:
    - ansible_facts.system == "Linux"

- name: "Install gmake (bsd)"
  become: true
  ansible.builtin.package:
    name:
      - gmake
  when:
    - ansible_facts.system in ['FreeBSD', 'OpenBSD']
