# vim: set ft=yaml.ansible:
---

- name: "Install make (Linux)"
  become: true
  ansible.builtin.package:
    name:
      - make
  when:
    - ansible_facts.system == "Linux"

- name: "Install gmake (bsd)"
  become: true
  ansible.builtin.package:
    name:
      - gmake
  when:
    - ansible_facts.system in ['FreeBSD', 'OpenBSD']

- name: "Set make_cmd = make (!bsd)"
  ansible.builtin.set_fact:
    make_cmd: make
  when:
    - ansible_facts.system not in ['FreeBSD', 'OpenBSD']

- name: "Set make_cmd = gmake (bsd)"
  ansible.builtin.set_fact:
    make_cmd: gmake
  when:
    - ansible_facts.system in ['FreeBSD', 'OpenBSD']
