# vim: set ft=yaml.ansible:
---

- name: "Enable EPEL repository (RedHat)"
  become: true
  block:
    - name: "Include role repo-epel"
      ansible.builtin.include_role:
        name: geerlingguy.repo-epel
  vars:
    epel_repo_disable: false
  when:
    - ansible_facts.os_family == 'RedHat'
    - ansible_facts.distribution not in ['Fedora', 'Amazon', 'Oracle']
