# vim: set ft=yaml.ansible:
---

- name: "Set releasever for RedHat family"
  ansible.builtin.set_fact:
    releasever: "{{ release[ansible_facts.distribution] + ansible_facts.distribution_major_version }}"
  vars:
    release:
      AlmaLinux: el
      Amazon: amzn
      CentOS: el
      Fedora: fc
      OracleLinux: ol
      Rocky: el
  when:
    - ansible_facts.os_family == "RedHat"

- name: "System details"
  ansible.builtin.debug:
    msg: |
      Distribution: {{ ansible_facts.distribution }}
      Version: {{ ansible_facts.distribution_version }}
      Major: {{ ansible_facts.distribution_major_version | default('n/a') }}
      Release: {{ ansible_facts.distribution_release }}
      Releasever: {{ releasever | default('n/a') }}

- name: "Set *.rpm package_file from package_dir"
  ansible.builtin.set_fact:
    package_file: "{{ package_dir }}/{{ releasever }}/RPMS/{{ ansible_facts.architecture }}/crowdsec-*.{{ releasever }}.{{ ansible_facts.architecture }}.rpm"
  when:
    - (package_dir is defined) and (package_dir | length > 0)
    - ansible_facts.os_family == "RedHat"

- name: "Set *.deb package_file from package_dir"
  ansible.builtin.set_fact:
    package_file: "{{ package_dir }}/{{ ansible_facts.distribution_release }}/crowdsec_*_{{ ansible_facts.architecture.replace('x86_64', 'amd64') }}.deb"
  when:
    - (package_dir is defined) and (package_dir | length > 0)
    - ansible_facts.os_family == "Debian"

- name: "Install from the package file"
  ansible.builtin.include_role:
    name: crowdsecurity.testing.install_package_from_file
