
#tasks file for roles/python

- name: install python dependencies
  package:
    - libffi-devel
    - zlib-devel
  when:
    - ansible_distribution == 'Fedora'
    - andible_distribution == 'CentOS' and ansible_distribution_version.startswith('7')

- name: Download and unpacking Python source
  unarchive:
    src: https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz
    dest: /tmp
    mode: 0755
    remote_src: yes

- name: Configure Python source
  shell: |
    ./configure --enable-optimization --with-ensurepip=install
  args:
    chdir: "/tmp/Python-{{ python_version }}"

- name: Compile Python
  shell: "make"
  args:
    chdir: "/tmp/Python-{{ python_version }}"

- name: Install Python
  become: true
  shell: "make install"
  args:
    chdir: "/tmp/Python-{{ python_version }}"
