#tasks file for roles/python
- name: Download and unpacking Python source
  unarchive:
#    src: https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python-version }}.tgz
    src: https://www.python.org/ftp/python/3.11.7/Python-3.11.7.tgz
    dest: /tmp
    mode: 0755
    remote_src: yes

- name: Configure Python source
  shell: |
    ./configure --enable-optimization --with-ensurepip=install
  args:
    chdir: "/tmp/Python-{{ python_version }}"

- name: Compile Python
  shell: "make"
  args:
    chdir: "/tmp/Python-{{ python_version }}"

- name: Install Python
  become: true
  shell: "make install"
  args:
    chdir: "/tmp/Python-{{ python_version }}"
