# vim: set ft=yaml.ansible:
---

- name: "Install binaries under test from the package repository"
  become: true
  block:
    - name: "Stable rpm repo script"
      ansible.builtin.get_url:
        url: https://install.crowdsec.net
        dest: "/root/script.sh"
        mode: 0o775

    - name: "Stable rpm repo"
      ansible.builtin.command:
        cmd: "/root/rpm.sh"
      changed_when: true

    - name: "Testing rpm repo"
      ansible.builtin.command:
        cmd: "/root/rpm-testing.sh"
      environment:
        repo: crowdsec-testing
      changed_when: true

    - name: "Dev rpm repo"
      ansible.builtin.command:
        cmd: "/root/rpm-dev.sh"
      environment:
        repo: crowdsec-dev
      changed_when: true

    - name: "Install package {{ binary_package_name }}"
      ansible.builtin.package:
        name:
          - "{{ binary_package_name }}-{{ package_version_rpm }}.el9 }}"
      when:
        - releasever != "amzn2"
        - releasever != "ol7"

    - name: "Install package {{ binary_package_name }}"
      ansible.builtin.package:
        name:
          - "{{ binary_package_name }}-{{ package_version_rpm }}.{{ releasever.replace('amzn2', 'el7').replace('ol7', 'el7') }}"
      when: releasever == "amzn2" or releasver == "ol7"
