# vim: set ft=yaml.ansible:
---

- name: "Install stuff"
  become: true
  ansible.builtin.package:
    name:
      - apt-transport-https
      - gnupg

- name: "Install binaries under test from the package repository"
  become: true
  block:
    - name: "Stable apt repo key"
      ansible.builtin.apt_key:
        url: https://packagecloud.io/crowdsec/crowdsec/gpgkey

    - name: "Stable apt repo"
      ansible.builtin.apt_repository:
        repo: deb https://packagecloud.io/crowdsec/crowdsec/any/ any main

    - name: "Testing apt repo key"
      ansible.builtin.apt_key:
        url: https://packagecloud.io/crowdsec/crowdsec-testing/gpgkey

    - name: "Testing apt repo"
      ansible.builtin.apt_repository:
        repo: deb https://packagecloud.io/crowdsec/crowdsec-testing/any/ any main

    - name: "Testing apt repo key"
      ansible.builtin.apt_key:
        url: https://packagecloud.io/crowdsec/crowdsec-dev/gpgkey
  
    - name: "Dev apt repo"
      ansible.builtin.apt_repository:
        repo: deb https://packagecloud.io/crowdsec/crowdsec-dev/any/ any main

    - name: "Install {{ binary_package_name }} {{ package_vesion_deb }} with apt"
      ansible.builtin.package:
        name:
          - "{{ binary_package_name }}={{ package_version_deb }}"


