# vim: set ft=yaml.ansible:
---

- name: "Set releasever for RedHat family"
  ansible.builtin.set_fact:
    releasever: "{{ release[ansible_facts.distribution] + ansible_facts.distribution_major_version }}"
  vars:
    release:
      AlmaLinux: el
      Amazon: amzn
      CentOS: el
      Fedora: fc
      OracleLinux: ol
      Rocky: el
  when:
    - ansible_facts.os_family == "RedHat"

- name: "System details"
  ansible.builtin.debug:
    msg: |
      Distribution: {{ ansible_facts.distribution }}
      Version: {{ ansible_facts.distribution_version }}
      Major: {{ ansible_facts.distribution_major_version | default('n/a') }}
      Release: {{ ansible_facts.distribution_release }}
      Releasever: {{ releasever | default('n/a') }}

- name: "Install from binary repository (RedHat)"
  ansible.builtin.import_tasks: install_from_rpm_repo.yml
  when:
    - (package_version_rpm is defined) and (package_version_rpm|length > 0)
    - ansible_facts.os_family == "RedHat"

- name: "Install from binary repository (Debian)"
  ansible.builtin.import_tasks: install_from_deb_repo.yml
  when:
    - (package_version_deb is defined) and (package_version_deb|length > 0)
    - ansible_facts.os_family == "Debian"
