# vim: set ft=yaml.ansible:
---

- name: "Install crowdsec from package_file"
  become: true
  block:
    - name: "Look for file matching package_file"
      ansible.builtin.set_fact:
        found_file: "{{ item }}"
      with_fileglob:
        - "{{ package_file }}"

    - name: "Check found_file"
      ansible.builtin.fail:
        msg: "No file found matching {{ package_file }}"
      when:
        - found_file is not defined

    - name: "Copy {{ found_file }}"
      ansible.builtin.copy:
        src: "{{ found_file }}"
        dest: "/root/crowdsec.rpm"
        mode: 0o644

    - name: "Install crowdsec"
      ansible.builtin.yum:
        name: "/root/crowdsec.rpm"
        disable_gpg_check: true
        allow_downgrade: true
  when:
    - (package_file is defined) and (package_file | length > 0)
