# vim: set ft=yaml.ansible:
---

- name: "Install Go (!bsd)"
  ansible.builtin.include_role:
    name: gantsign.golang
  when:
    - ansible_facts.system == 'Linux'
    - ansible_facts.distribution != 'Alpine'

- name: "Install Go (bsd, alpine)"
  become: true
  ansible.builtin.package:
    name: go
    state: present
  when:
    - ansible_facts.system in ['FreeBSD', 'OpenBSD'] or ansible_facts.distribution == 'Alpine'
