# vim: set ft=yaml.ansible:
---

- name: "Check if we need to build bash"
  become: false
  block:
    - name: "Look up bash version"
      ansible.builtin.package_facts:

    - name: "Bash version found"
      ansible.builtin.debug:
        var: ansible_facts.packages['bash'][0].version

    - name: "Check if bash is too old (<4.4)"
      ansible.builtin.set_fact:
        build_bash: "{{ ansible_facts.packages['bash'][0].version is version('4.4', '<') }}"

- name: "Build bash"
  block:
    - name: "Build bash: download"
      become: false
      ansible.builtin.unarchive:
        src: http://ftp.gnu.org/gnu/bash/bash-{{ bash_version }}.tar.gz
        dest: "{{ ansible_env.HOME }}"
        remote_src: true
        creates: "{{ ansible_env.HOME }}/bash-{{ bash_version }}"

    - name: "Build bash: configure"
      become: false
      ansible.builtin.command:
        cmd: "./configure --prefix=/opt/bash"
        creates: ./Makefile
        chdir: "{{ ansible_env.HOME }}/bash-{{ bash_version }}"

    - name: "Build bash: create /opt/bash"
      become: true
      ansible.builtin.file:
        path: /opt/bash
        state: directory
        mode: 0o755

    - name: "Build bash: make install"
      become: true
      ansible.builtin.command:
        cmd: "make install"
        creates: /opt/bash/bin/bash
        chdir: "{{ ansible_env.HOME }}/bash-{{ bash_version }}"
  when:
    - build_bash
