# vim: set ft=yaml.ansible:
---

- name: "Install daemonize package"
  become: true
  ansible.builtin.package:
    name:
      - daemonize
  when:
    - not build_daemonize

- name: "Build daemonize"
  block:
    - name: "Build daemonize: git checkout"
      become: false
      ansible.builtin.git:
        repo: https://github.com/bmc/daemonize
        dest: "{{ ansible_env.HOME }}/daemonize"
        version: release-1.7.8

    - name: "Build daemonize: configure"
      become: false
      ansible.builtin.command:
        cmd: "./configure --prefix=/usr/local"
        creates: ./Makefile
        chdir: "{{ ansible_env.HOME }}/daemonize"

    - name: "Build daemonize: make install (linux)"
      become: true
      ansible.builtin.command:
        cmd: "make all install"
        creates: /usr/local/sbin/daemonize
        chdir: "{{ ansible_env.HOME }}/daemonize"
      when:
        - ansible_facts.system == 'Linux'

    - name: "Build daemonize: make install (bsd)"
      become: true
      ansible.builtin.command:
        cmd: "gmake all install"
        creates: /usr/local/sbin/daemonize
        chdir: "{{ ansible_env.HOME }}/daemonize"
      when:
        - ansible_facts.system in ['FreeBSD', 'OpenBSD']
  when:
    - build_daemonize
