# vim: set ft=yaml.ansible:
---

- name: "Install bash"
  ansible.builtin.import_tasks: bash.yml
  when:
    # openbsd is not supported by the package_facts module, let's assume bash is ok
    - ansible_facts.system != 'OpenBSD'

- name: "Install daemonize"
  ansible.builtin.import_tasks: daemonize.yml

- name: "Install netcat"
  ansible.builtin.import_tasks: netcat.yml

- name: "Install curl, jq, openssl, python3"
  become: true
  ansible.builtin.package:
    name:
      - curl
      - jq
      - openssl
      - python3
  when:
    - ansible_facts.distribution != 'Gentoo'

- name: "Install bc (!freebsd)"
  become: true
  ansible.builtin.package:
    name:
      - bc
  when:
    - ansible_facts.system == 'Linux'

# base64 for linux is in coreutils
- name: "Install base64 (bsd)"
  become: true
  ansible.builtin.package:
    name:
      - base64
  when:
    - ansible_facts.system in ['FreeBSD', 'OpenBSD']

- name: "Install pidof (Amazon)"
  become: true
  ansible.builtin.package:
    name:
      - procps-ng
  when:
    - ansible_facts.distribution == 'Amazon'

- name: "Install cfssl"
  become: true
  ansible.builtin.command:
    cmd: "go install github.com/cloudflare/cfssl/cmd/cfssl@latest"
    creates: /usr/bin/cfssl
  environment:
    GOBIN: /usr/bin
    # make sure we use the built version of go, if there is one
    PATH: "{{ golang_install_dir }}/bin:{{ ansible_env.PATH }}"

- name: "Install cfssljson"
  become: true
  ansible.builtin.command:
    cmd: "go install github.com/cloudflare/cfssl/cmd/cfssljson@latest"
    creates: /usr/bin/cfssljson
  environment:
    GOBIN: /usr/bin
    # make sure we use the built version of go, if there is one
    PATH: "{{ golang_install_dir }}/bin:{{ ansible_env.PATH }}"

- name: "Install yq"
  become: true
  ansible.builtin.command:
    cmd: "go install github.com/mikefarah/yq/v4@latest"
    creates: /usr/bin/yq
  environment:
    GOBIN: /usr/bin
    # make sure we use the built version of go, if there is one
    PATH: "{{ golang_install_dir }}/bin:{{ ansible_env.PATH }}"
