# vim: set ft=yaml.ansible:
---

- name: "Install netcat (Amazon, Fedora, CentOS, Oracle)"
  become: true
  ansible.builtin.package:
    name:
      - nmap-ncat
  when:
    - ansible_facts.distribution in ['Amazon',  'Fedora', 'CentOS', 'OracleLinux']

- name: "Install netcat (RedHat)"
  become: true
  ansible.builtin.package:
    name:
      - netcat
  when:
    - (ansible_facts.distribution == 'RedHat') or (ansible_facts.distribution == 'AlmaLinux') or (ansible_facts.distribution == 'Rocky')

# "netcat" does not exist in some Debian versions (only -traditional or -openbsd)
- name: "Install netcat (Suse)"
  become: true
  ansible.builtin.package:
    name:
      - netcat-openbsd
  when:
    - ansible_facts.os_family in ["Debian", "Suse"]
